package ssl.hanshake.retofit.exceptions;

public enum HandShakeError {

    NO_URL_FOUND,
    NO_PUBLIC_KEY_FOUND,
    NO_MODE_FOUND,
    PUBLIC_KEY_EXTRACT_ERROR,
    NO_CERTIFICATE_FOUND,
    CERTIFICATE_FILE_NOT_FOUND,
    INVALID_URL,
    CERTIFICATE_ALGORITHM_ERROR,
    CERTIFICATE_KEY_ERROR,

}
